project:
  title: "Research Template"
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.ts   # remove previously constructed files
  output-dir: _products
  render:
    # if analysis is split into multiple docs, add them here
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    - "!bibliography/"
  execute-dir: project

author:
  - name: Aaron Gullickson
    orcid: 0000-0001-7237-8131
    email: aarong@uoregon.edu
    url: https://aarongullickson.netlify.app/
    attributes:
      corresponding: true
    affiliations:
      - id: uo
        name: University of Oregon
        department: Sociology
        address: 727 PLC
        city: Eugene
        region: OR
        country: USA
        postal-code: 97405
  
execute: 
  freeze: false
  
editor: source

bibliography: bibliography/project.bib
csl: bibliography/chicago-parenthetical.csl




