project:
  title: "Research Template"
  pre-render: 
    - utils/check_packages.R
    - rm -r data/data_constructed
    - mkdir data/data_constructed
    - rm -r _products      # refresh products directory to prevent artifacts
  output-dir: _products
  render:
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/

author:
  - name: Aaron Gullickson
    orcid: 0000-0001-7237-8131
    email: aarong@uoregon.edu
    url: https://aarongullickson.netlify.app/
    attributes:
      corresponding: true
    affiliations:
      - id: uo
        name: University of Oregon
        department: Sociology
        address: 727 PLC
        city: Eugene
        region: OR
        country: USA
        postal-code: 97405
  
execute: 
  freeze: false
  
editor: source

bibliography: project.bib




