project:
  title: "Research Template"
  # the default output directory is _docs. If you want to serve up 
  # the results here from GitHub Pages, it might be easier to use docs,
  # but I prefer the underscore to keep consistent with quarto project
  # syntax
  output-dir: _docs
  execute-dir: project
  
  # determine which files to run when project is built and their order
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.R    # remove previously constructed files
  render:
    - index.qmd
    # if analysis is split into multiple docs, add them here, specifying 
    # individual qmd files also allows us to ensure proper ordering of 
    # when they run (e.g. organize_data before analysis)
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    # uncomment out next line to get a site index for your project
    - "!bibliography/"
    
# bibliography information. You can add additional CSL styles to the 
# bibliography directory and use them.
reference-section-title: References
bibliography: bibliography/project.bib
csl: bibliography/chicago-parenthetical.csl


# list all authors here in separate bullets
author:
  - name: Aaron Gullickson
    orcid: 0000-0001-7237-8131
    email: aarong@uoregon.edu
    url: https://aarongullickson.netlify.app/
    attributes:
      corresponding: true
    affiliations:
      - name: University of Oregon
        department: Sociology
        address: 727 PLC
        city: Eugene
        region: OR
        country: USA
        postal-code: 97405

execute: 
  freeze: false
  
editor: source



